apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialbeernetwork
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialbeernetwork
  template:
    metadata:
      labels:
        app: socialbeernetwork
    spec:
      containers:
      - name: frontend
        image: ghcr.io/timbenedet/socialbeernetwork:main-6945edd
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: socialbeernetwork
  namespace: default
spec:
  selector:
    app: socialbeernetwork
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30086
  type: NodePort
